export const selectOptionsUpdateProduct = {
  yield_value: ["Select", "Correct", "Bon", "Très bon", "Excellent"],
  strate_value: [
    "Select",
    "Arbre",
    "Arbuste",
    "Herbacés haute",
    "Herbacés basse",
    "Couvre-sol",
    "Racine",
    "Grimpante",
  ],
  hardiness_zone_value: [
    "Select",
    "Zone 1a : -51,1 à -48,3°C",
    "Zone 1b : -48,3 à -45,6°C",
    "Zone 2a : -45,6 à -42,8°C",
    "Zone 2b : -42,8 à -40°C",
    "Zone 3a : -40 à -37,2°C",
    "Zone 3b : -37,2 à -34,4°C",
    "Zone 4a : -34,4 à -31,7°C",
    "Zone 4b : -31,7 à -28,9°C",
    "Zone 5a : -28,9 à -26,1°C",
    "Zone 5b : -26,1 à -23,3°C",
    "Zone 6a : -23,3 à -20,6°C",
    "Zone 6b : -20,6 à -17,8°C",
    "Zone 7a : -17,8 à -15°C",
    "Zone 7b : -15 à -12,2°C",
    "Zone 8a : -12,2 à -9,4°C",
    "Zone 8b : -9,4 à -6,7°C",
    "Zone 9a : -6,7 à -3,9°C",
    "Zone 9b : -3,9 à -1,1°C",
    "Zone 10a : -1,1 à 1,7°C",
    "Zone 10b : 1,7 à 4,4°C",
    "Zone 11a : 4,4 à 7,2°C",
    "Zone 11b : 7,2 à 10°C",
    "Zone 12a : 10 à 12,8°C",
    "Zone 12b : 12,8 à 15,6°C",
    "Zone 13a : 15,6 à 18,3°C",
    "Zone 13b : 18,3 à 21,1°C",
  ],
  water_requirement_value: ["Select", "Faible", "Moyen", "Fort"],
  exposure_value: [
    "Select",
    "Plein Soleil",
    "Ombre légère",
    "Ombre modérée",
    "Pleine ombre",
    "Ombre profonde",
  ],
  ground_cover_power_value: [
    "Select",
    "Mauvais",
    "Correct (Désherbage printemps/été)",
    "Bon",
    "Très bon",
    "Non couvrant",
  ],
  foliage_value: ["Select", "Persistant", "Caduc", "Persistant et caduc"],
  status: ["Select", "Disponible", "Indisponible"],
  category: [
    "Select",
    "Aromates et Médicinales",
    "Fruitiers",
    "Agrumes",
    "Aromates et Médicinales",
  ],
};
